# Generated by Django 3.2.16 on 2022-11-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20221115_0056'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='user_recipes',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='users',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='user_recipes'),
        ),
    ]
